name: Backend Continuous Integration Workflow

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  lint:
    name: Backend Linting Jobs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache pipenv dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pipenv
          key: pipenv-${{ runner.os }}-${{ hashFiles('backend/Pipfile.lock') }}
          restore-keys: |
            pipenv-${{ runner.os }}-

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: |
          pip --version
          pipenv install && pip install flake8
        working-directory: ./backend

      - name: Run lint with pipenv
        run: |
          pipenv --version
          pipenv run lint
        working-directory: ./backend

  test:
    name: Backend Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          pip --version
          pip install pipenv
        working-directory: ./backend

      - name: Install dependencies
        run: |
          pip --version
          pipenv install
        working-directory: ./backend

      - name: Run tests with pipenv
        run: |
          pipenv --version
          pipenv run test
        working-directory: ./backend

  build:
    name: Build and Push Image to ECR
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pipenv
        run: |
          pip --version
          pip install pipenv && pip install flake8
        working-directory: ./backend

      - name: Install dependencies
        run: |
          pip --version
          pipenv install
        working-directory: ./backend

      - name: Verify Dockerfile
        run: |
          ls -l ./backend/Dockerfile
        working-directory: ./backend

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: "true"

      - name: Build and Push Docker Image to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: backend
          IMAGE_TAG: latest
        run: |
          echo "Building Docker image: $REGISTRY/$REPOSITORY:$IMAGE_TAG"
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG -f ./backend/Dockerfile ./backend
          docker images

      - name: Cache Docker Image
        uses: actions/cache@v3
        with:
          path: ~/.docker
          key: docker-${{ github.sha }}-backend
          restore-keys: |
            docker-${{ github.sha }}-
